<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Personnel Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9c9b1b44-5201-4f53-8899-62826743453a</testSuiteGuid>
   <testCaseLink>
      <guid>dac8032f-2545-4213-90c3-004b14e653fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login and Logout/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>420751b5-4d56-4286-b833-ece9d3c9bc18</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f4b2d0f-f957-4dd3-ae1e-00a7d3b30efe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8abf0bdb-0dc1-45d6-bb34-b5d5b65d2563</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91f164fe-6cb2-4a61-acea-f6bcfc754673</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Personnel/Verify Mandatory Fields - Personnel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>47fcd5ad-35db-48df-bc82-faf495fe7521</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Personnel/Create Personnel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a38743f-d0df-43d6-96a2-d2ef3e6f3299</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8ef80ae-fc80-40a0-8ebc-ff3e89994be5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Personnel/View and Edit Personnel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>235ebf7d-4253-491e-baa6-b716d6d6f750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7507fb78-737e-4569-a95f-fb12902f33e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83dda414-c818-47a6-b1fa-5e77b3ad508f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
